project:
  type: website
  output-dir: docs


website:
  title: "wesbite-demo1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

